networks:
  zugnet:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  db:
    image: postgres:14-alpine
    container_name: peon.db
    hostname: peon.db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
    volumes:
      - $PWD/db:/var/lib/postgresql/data
      - /var/log/peon:/var/log/peon
    networks:
      zugnet:
        ipv4_address: 172.20.0.2
    restart: unless-stopped
    labels:
      com.peon.description: "Peon backend DB (PostgreSQL)"
  webapp:
    container_name: peon.ui
    hostname: peon.ui
    image: umlatt/peon.ui:0.1.5-dev
    depends_on:
      - db
    ports:
      - '80:80'
    volumes:
      - /var/log/peon:/var/log/peon
    networks:
      zugnet:
        ipv4_address: 172.20.0.3
    restart: unless-stopped
  orchestrator:
    container_name: peon.orc
    hostname: peon.orc
    image: umlatt/peon.orc:0.2.13-dev
    depends_on:
      - db
    ports:
      - '5000:5000'
    volumes:
      - /var/log/peon:/var/log/peon
      - $PWD/servers:/root/peon/servers
      - $PWD/plans:/root/peon/plans
      - $PWD/certs:/root/peon/certs
    networks:
      zugnet:
        ipv4_address: 172.20.0.4
    restart: unless-stopped
    privileged: true
  rest_api_viewer:
    container_name: peon.dev.api.docs
    hostname: peon.dev.api.docs
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=${SWAGGER_JSON}
    depends_on:
      - orchestrator
    ports:
      - '8080:8080'
    volumes:
      - $PWD/documentation/api/1.0:/mnt
    networks:
      zugnet:
        ipv4_address: 172.20.0.5
    restart: unless-stopped
  bot.discord:
    container_name: peon.bot.discord
    hostname: peon.bot.discord
    image: umlatt/peon.bot.discord:0.2.3-dev
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    depends_on:
      - orchestrator
    volumes:
      - /var/log/peon:/var/log/peon
      - $PWD/config:/app/config
    networks:
      zugnet:
        ipv4_address: 172.20.0.20
    restart: unless-stopped