version: '3.8'
networks:
  peon.zugnet:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  db:
    image: postgres:14-alpine
    container_name: peon.db
    environment:
      - POSTGRES_USER=peonadmin
      - POSTGRES_PASSWORD=Zu88Zu88
    volumes:
      - $PWD/peon/db/data:/var/lib/postgresql/data
      - /var/log/peon:/var/log/peon
    networks:
      peon.zugnet:
        ipv4_address: 172.20.0.2
    restart: always
  webapp:
    container_name: peon.webui
    image: umlatt/peon-ui
    depends_on:
      - db
    ports:
      - '80:80'
    volumes:
      - /var/log/peon:/var/log/peon
    networks:
      peon.zugnet:
        ipv4_address: 172.20.0.3
    restart: unless-stopped