networks:
  zugnet:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  db:
    image: postgres:14-alpine
    container_name: peon.db
    environment:
      - POSTGRES_DB=durotar
      - POSTGRES_USER=gromhellscream
      - POSTGRES_PASSWORD=Zu88Zu88
    volumes:
      - $PWD/db:/var/lib/postgresql/data
      - /var/log/peon:/var/log/peon
    networks:
      zugnet:
        ipv4_address: 172.20.0.2
    restart: always
    command: bash -c cd /var/lib/postgresql/data & sed -i "$(cat -n pg_hba.conf | grep 127.0.0.1/32 | grep -v replication | awk '{print $1}') a host    all             gromhellscream  172.20.0.0/24           md5" pg_hba.conf
  webapp:
    container_name: peon.ui
    image: umlatt/peon.ui:0.1.1-dev
    depends_on:
      - db
    ports:
      - '80:80'
    volumes:
      - /var/log/peon:/var/log/peon
    networks:
      zugnet:
        ipv4_address: 172.20.0.3
    restart: unless-stopped
  orchestrator:
    container_name: peon.orc
    image: umlatt/peon.orc:0.1.4-dev
    depends_on:
      - db
    ports:
      - '5000:5000'
    volumes:
      - /var/log/peon:/var/log/peon
      - $PWD/servers:/servers
      - $PWD/plans:/plans
    networks:
      zugnet:
        ipv4_address: 172.20.0.4
    restart: unless-stopped
    privileged: true
