  orc:
    container_name: peon.orc
    hostname: peon.orc
    environment:
      - DEV_MODE=${DEV_MODE}
      - HOST_DIR=${PEON_DIRECTORY}
    image: umlatt/peon.orc:latest
    ports:
      - '5000:5000'
    volumes:
      - /var/log/peon:/var/log/peon
      - $PWD/servers:/home/peon/servers
      - $PWD/plans:/home/peon/plans
      - $PWD/certs:/home/peon/certs
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
    networks:
      zugnet:
        ipv4_address: 172.20.0.2
    restart: unless-stopped
    privileged: true
