  db:
    image: postgres:14-alpine
    container_name: peon.db
    hostname: peon.db
    environment:
      - DEV_MODE=${DEV_MODE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
    volumes:
      - $PWD/db:/var/lib/postgresql/data
      - /var/log/peon:/var/log/peon
    networks:
      zugnet:
        ipv4_address: 172.20.0.3
    restart: unless-stopped
    labels:
      com.peon.description: "Peon backend DB (PostgreSQL)"
  webapp:
    container_name: peon.webui
    hostname: peon.webui
    image: umlatt/peon.webui:latest
    depends_on:
      - db
    ports:
      - '80:80'
    networks:
      zugnet:
        ipv4_address: 172.20.0.4
    restart: unless-stopped
