  bot.discord:
    container_name: peon.bot.discord
    hostname: peon.bot.discord
    image: umlatt/peon.bot.discord
    environment:
      - DEV_MODE=${DEV_MODE}
      - DISCORD_TOKEN='${DISCORD_TOKEN}'
      - LOCAL_API_KEY='${PEON_API_KEY:-}'
    volumes:
      - $PWD/config:/app/config
    networks:
      zugnet:
        ipv4_address: 172.20.0.20
    restart: unless-stopped
    depends_on:
      - orc
