version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=S3CR3TP4$$W0RD
    ports:
      - '5432:5432'
    volumes: 
      - $PWD/data:/var/lib/postgresql/data
